import { expect, test } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

test('Delete Daily', async ({ page }) => {
    await page.goto(process.env.API_URL);
    await page.locator(`input[name="${process.env.GOOGLE_CALENDAR}"]`).check();
    await page.locator(`input[name="${process.env.MICROSOFT_CALENDAR}"]`).uncheck();
    await page.locator('.offcanvas-backdrop').click();
    await page.waitForTimeout(5000);
    const calendarEvent = page.locator('#E-20250904');
    await expect(calendarEvent).toBeVisible({ timeout: 10000 });
    await calendarEvent.click();
    await page.getByRole('button', { name: 'Daily Repeat Sep 4 - 5, All' }, { timeout: 30000 }).first().click();
    await page.getByRole('button').filter({ hasText: /^Loading\.\.\.$/ }).nth(3).click();
    await page.getByRole('button', { name: 'Delete Event' }).click();
    await expect(page.getByText('Event deleted successfully')).toBeVisible({ timeout: 10000 });
});
test('Delete Weekly', async ({ page }) => {
    await page.goto(process.env.API_URL);
    await page.locator(`input[name="${process.env.GOOGLE_CALENDAR}"]`).check();
    await page.locator(`input[name="${process.env.MICROSOFT_CALENDAR}"]`).uncheck();
    await page.locator('.offcanvas-backdrop').click();
    await page.waitForTimeout(5000);
    const calendarEvent = page.locator('#E-20250904');
    await expect(calendarEvent).toBeVisible({ timeout: 10000 });
    await calendarEvent.click();
    await page.getByRole('button', { name: 'Weekly Repeat Sep 4 - 5, All' }).click();
    await page.getByRole('button').filter({ hasText: /^Loading\.\.\.$/ }).nth(3).click();
    await page.getByRole('button', { name: 'Delete Event' }).click();
    await expect(page.getByText('Event deleted successfully')).toBeVisible({ timeout: 10000 });
});
test('Delete Monthly', async ({ page }) => {
    await page.goto(process.env.API_URL);
    await page.locator(`input[name="${process.env.GOOGLE_CALENDAR}"]`).check();
    await page.locator(`input[name="${process.env.MICROSOFT_CALENDAR}"]`).uncheck();
    await page.locator('.offcanvas-backdrop').click();
    await page.waitForTimeout(5000);
    const calendarEvent = page.locator('#E-20250904');
    await expect(calendarEvent).toBeVisible({ timeout: 10000 });
    await calendarEvent.click();
    await page.getByRole('button', { name: 'Monthly Repeat Sep 4 - 5, All' }).click();
    await page.getByRole('button').filter({ hasText: /^Loading\.\.\.$/ }).nth(3).click();
    await page.getByRole('button', { name: 'Delete Event' }).click();
    await expect(page.getByText('Event deleted successfully')).toBeVisible({ timeout: 10000 });
});
test('Delete Annually', async ({ page }) => {
    await page.goto(process.env.API_URL);
    await page.locator(`input[name="${process.env.GOOGLE_CALENDAR}"]`).check();
    await page.locator(`input[name="${process.env.MICROSOFT_CALENDAR}"]`).uncheck();
    await page.locator('.offcanvas-backdrop').click();
    await page.waitForTimeout(5000);
    const calendarEvent = page.locator('#E-20250904');
    await expect(calendarEvent).toBeVisible({ timeout: 10000 });
    await calendarEvent.click();
    await page.getByRole('button', { name: 'Annually Repeat Sep 4 - 5, All' }).click();
    await page.getByRole('button').filter({ hasText: /^Loading\.\.\.$/ }).nth(3).click();
    await page.getByRole('button', { name: 'Delete Event' }).click();
    await expect(page.getByText('Event deleted successfully')).toBeVisible({ timeout: 10000 });
});
